{% set version = "6.1.0" %}
{% set met_version = "12.1.0" %}

package:
  name: metplus
  version: {{ version }}

source:
  - url: https://github.com/dtcenter/METplus/archive/refs/tags/v{{ version }}.tar.gz
    md5: fdde657734168a93f002039862b69144
    sha256: f79552f18d439e416dfa4f7cb65de9f1196864c5d3abf7443310ae4a154cc15f

  - url: https://github.com/dtcenter/MET/archive/refs/tags/v{{ met_version }}.tar.gz
    md5: 972fdb929868e0f9d799af4ca9a4eeb2
    sha256: c0d25ab44255f83e4dbc8f472eaa1cf44f5a05d8a6a260c5c4f1811f2da457c7
    folder: MET


build:
  skip: true  # [win or py!=310]
  number: 0
  entry_points:
    - run_metplus.py = metplus.scripts.run_metplus:cli_main
  ignore_run_exports:
    - numpy


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - gnuconfig

  host:
    - python
    - pip
    - gsl
    - netcdf-cxx4
    - zlib
    - cairo
    - freetype
    - nceplibs-bufr
    - nceplibs-g2c
    - metview
    - hdfeos2
    - setuptools
    - setuptools-git-versioning >=2.0,<3
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  run:
    - gsl
    - netcdf-cxx4
    - python
    - nceplibs-bufr
    - nceplibs-g2c
    - hdf4
    - metview
    - xarray
    - numpy >=1.24,<2
    - pandas
    - pyyaml
    - netcdf4
    - scipy
    - libopenblas  # [linux]

test:
  commands:
    - $PREFIX/bin/ascii2nc
    - test -f $PREFIX/bin/ensemble_stat
    - test -f $PREFIX/bin/gen_ens_prod
    - test -f $PREFIX/bin/gen_vx_mask
    - test -f $PREFIX/bin/grid_diag
    - test -f $PREFIX/bin/grid_stat
    - test -f $PREFIX/bin/ioda2nc
    - test -f $PREFIX/bin/lidar2nc
    - test -f $PREFIX/bin/madis2nc
    - test -f $PREFIX/bin/mode
    - test -f $PREFIX/bin/mode_analysis
    - test -f $PREFIX/bin/mtd
    - test -f $PREFIX/bin/pair_stat
    - test -f $PREFIX/bin/pb2nc
    - test -f $PREFIX/bin/pcp_combine
    - test -f $PREFIX/bin/plot_data_plane
    - test -f $PREFIX/bin/plot_point_obs
    - test -f $PREFIX/bin/point2grid
    - test -f $PREFIX/bin/point_stat
    - test -f $PREFIX/bin/regrid_data_plane
    - test -f $PREFIX/bin/rmw_analysis
    - test -f $PREFIX/bin/series_analysis
    - test -f $PREFIX/bin/stat_analysis
    - test -f $PREFIX/bin/tc_diag
    - test -f $PREFIX/bin/tc_gen
    - test -f $PREFIX/bin/tc_pairs
    - test -f $PREFIX/bin/tc_rmw
    - test -f $PREFIX/bin/tc_stat
    - test -f $PREFIX/bin/wavelet_stat
  imports:
    - metplus


about:
  home: https://dtcenter.org/community-code/metplus
  summary: 'Unified NWP model verification, validation, and diagnostic tools'
  description: |
    This module includes the MET C++ executables and the METplus Wrappers
    Python suite.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.md
    - MET/LICENSE.md
  doc_url: https://metplus.readthedocs.io
  dev_url: https://github.com/dtcenter/METplus

extra:
  recipe-maintainers:
    - georgemccabe
