{% set version = "6.2.0" %}
{% set met_version = "12.2.0" %}

package:
  name: metplus
  version: {{ version }}

source:
  - url: https://github.com/dtcenter/METplus/archive/refs/tags/v{{ version }}.tar.gz
    md5: fc5e36592e163f1c88b2d33f38a7ab10
    sha256: 2356e6639616484ddc5a23d4948e953e4d637fa4cc59763c239f116105e7e82e

  - url: https://github.com/dtcenter/MET/archive/refs/tags/v{{ met_version }}.tar.gz
    md5: 2ad2b1df79576c23e4bd2a7e0a7c62bb
    sha256: 915ae77f06e83210158de703c11daf0f0d8e7a9223433487e37cac6284b417dd
    folder: MET
    patches:
      - met_regex.patch


build:
  skip: true  # [win or py<310]
  number: 0
  entry_points:
    - run_metplus.py = metplus.scripts.run_metplus:cli_main
  ignore_run_exports:
    - numpy


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - gnuconfig

  host:
    - python
    - pip
    - gsl
    - netcdf-cxx4
    - zlib
    - cairo
    - freetype
    - nceplibs-bufr
    - nceplibs-g2c
    - metview ==5.25.1
    - hdfeos2
    - setuptools
    - setuptools-git-versioning >=2.0,<3
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  run:
    - gsl
    - netcdf-cxx4
    - python
    - nceplibs-bufr
    - nceplibs-g2c
    - hdf4
    - metview ==5.25.1
    - xarray
    - numpy
    - pandas
    - pyyaml
    - netcdf4
    - scipy
    - libopenblas  # [linux]

test:
  commands:
    - $PREFIX/bin/ascii2nc --help
    - $PREFIX/bin/ensemble_stat --help
    - $PREFIX/bin/gen_ens_prod --help
    - $PREFIX/bin/gen_vx_mask --help
    - $PREFIX/bin/grid_diag --help
    - $PREFIX/bin/grid_stat --help
    - $PREFIX/bin/ioda2nc --help
    - $PREFIX/bin/lidar2nc --help
    - $PREFIX/bin/madis2nc --help
    - $PREFIX/bin/mode --help
    - $PREFIX/bin/mode_analysis --help
    - $PREFIX/bin/mtd --help
    - $PREFIX/bin/pair_stat --help
    - $PREFIX/bin/pb2nc --help
    - $PREFIX/bin/pcp_combine --help
    - $PREFIX/bin/plot_data_plane --help
    - $PREFIX/bin/plot_point_obs --help
    - $PREFIX/bin/point2grid --help
    - $PREFIX/bin/point_stat --help
    - $PREFIX/bin/regrid_data_plane --help
    - $PREFIX/bin/rmw_analysis --help
    - $PREFIX/bin/series_analysis --help
    - $PREFIX/bin/stat_analysis --help
    - $PREFIX/bin/tc_diag --help
    - $PREFIX/bin/tc_gen --help
    - $PREFIX/bin/tc_pairs --help
    - $PREFIX/bin/tc_rmw --help
    - $PREFIX/bin/tc_stat --help
    - $PREFIX/bin/wavelet_stat --help
  imports:
    - metplus


about:
  home: https://dtcenter.org/community-code/metplus
  summary: 'Unified NWP model verification, validation, and diagnostic tools'
  description: |
    This module includes the MET C++ executables and the METplus Wrappers
    Python suite.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.md
    - MET/LICENSE.md
  doc_url: https://metplus.readthedocs.io
  dev_url: https://github.com/dtcenter/METplus

extra:
  recipe-maintainers:
    - georgemccabe
